apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ts-seat-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ts-seat-service
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 960Mi
