apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ts-travel2-mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ts-travel2-mongo
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 400Mi
